name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:5.7
        env:
          MYSQL_ROOT_USER: root
          MYSQL_ROOT_PASSWORD: ZkdiwZe38Gsd
          MYSQL_USER: toyeight
          MYSQL_PASSWORD: 87sjbS2dBmzd
          MYSQL_DATABASE: school_db
          MYSQL_HOST: db
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3
      - name: Copy .env
        run: |
          cp .env.example .env
      - name: Build the Docker image
        run: |
          docker build -t myapp .
      - name: Run the Docker image
        run: |
          docker-compose -f compose.yml up -d
      - name: Setup laravel environment
        run: cp .env.example .env
        working-directory: src/
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
        working-directory: src/
      - name: Generate key
        run: php artisan key:generate
        working-directory: src/
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
        working-directory: src/
      - name: Migrate DB
        run: |
          php artisan migrate --force
          php artisan db:seed
        working-directory: src/
