name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Copy .env
        run: |
          cp .env.example .env
      - name: Build the Docker image
        run: |
          run: |
            docker build -t .
      - name: Run the Docker image
        run: |
          docker-compose -f compose.yml up -d
      #- name: Setup laravel and migrate database
      #  run: |
      #    cd src
      #    cp .env.example .env
      #    docker exec -i toyeight.app bash
      #    composer install
      #    php artisan key:generate
      #    php artisan migrate --force
      #    php artisan db:seed
