name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Copy .env
      run: |
        cp .env.example .env
    - name: Build the Docker image
      run: |
        docker build -t school:api -f ./docker/php/Dockerfile.
    - name: Run the Docker image
      run: |
        docker run school:api
