name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Copy .env
      run: |
        cp .env.example .env
    - name: Build the Docker image
      run: |
        run: |
          cd ./docker/php/
          docker build -t myapp ./docker/php/
        working-directory: ./docker/php/
    - name: Run the Docker image
      run: |
        docker run --rm myapp vendor/bin/phpunit
