name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:5.7
        env:
          MYSQL_ROOT_USER: root
          MYSQL_ROOT_PASSWORD: ZkdiwZe38Gsd
          MYSQL_USER: toyeight
          MYSQL_PASSWORD: 87sjbS2dBmzd
          MYSQL_DATABASE: school_db
          MYSQL_HOST: db
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3
      - name: Create new directory
        run: |
          mkdir Report
      - name: Install Node.js and Newman
        run: |
          curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
          sudo apt-get install -y nodejs
          npm install -g newman
          npm install -g newman-reporter-slackreporter
          npm install -g newman-reporter-htmlextra
        # This step installs Node.js and Newman on the GitHub Actions runner.
      - name: Copy .env
        run: |
          cp .env.example .env
      - name: Build the Docker image
        run: |
          run: |
            docker build -t myapp .
      - name: Run the Docker image
        run: |
          docker-compose -f compose.yml up -d

          # Sleep for a few seconds to ensure containers are up and running
          sleep 5

          # Get container IDs
          container_ids=$(docker ps -q)

          # Loop through container IDs and print host and port information
          for container_id in $container_ids; do
            container_host=$(docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $container_id)
            container_port=$(docker inspect --format='{{range $port, $conf := .NetworkSettings.Ports}}{{if eq $port "80/tcp"}}{{$conf.[0].HostPort}}{{end}}{{end}}' $container_id)
            echo "Container ID: $container_id, Host: $container_host, Port: $container_port"
          done
      - name: Setup laravel environment
        run: cp .env.example .env
        working-directory: src/
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
        working-directory: src/
      - name: Generate key
        run: php artisan key:generate
        working-directory: src/
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
        working-directory: src/
      - name: Migrate DB
        run: |
          php artisan migrate --force
          php artisan db:seed
        working-directory: src/
      - name: Run API test
        run: |
          newman run "api/test/School_API.postman_collection.json" -e "api/test/School.postman_environment.json" -r cli,htmlextra --reporter-htmlextra-export Report/report.html
      - name: Upload the report
        uses: actions/upload-artifact@v3
        with:
          name: Report
          path: Report
      - name: Psalm Security Scan
        uses: psalm/psalm-github-security-scan@f3e6fd9432bc3e44aec078572677ce9d2ef9c287
      - name: Upload Security Analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
