name: Laravel

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:5.7
        env:
          MYSQL_ROOT_USER: root
          MYSQL_ROOT_PASSWORD: ZkdiwZe38Gsd
          MYSQL_USER: toyeight
          MYSQL_PASSWORD: 87sjbS2dBmzd
          MYSQL_DATABASE: school_db
          MYSQL_HOST: db
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.1"
      - uses: actions/checkout@v3
      - name: Copy .env
        run: cp .env.example .env
        working-directory: src/
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
        working-directory: src/
      - name: Generate key
        run: php artisan key:generate
        working-directory: src/
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
        working-directory: src/
      - name: Migrate DB
        run: |
          php artisan migrate --force
          php artisan db:seed
          php artisan config:cache
        working-directory: src/
      - name: Run Static Analysis
        run: |
          ./vendor/bin/psalm
        working-directory: src/
      - name: Check host and port
        run: |
          netstat -a
      - name: Test availability
        run: |
          curl -X POST http://localhost:8084/api/register \
          -H "Accept:application/json" \
          -H "Content-Type:application/json" \
          -d '{"name": "John", "email": "john.doe@toptal.com", "password": "toptal123", "password_confirmation": "toptal123"}'
      - name: Create new directory
        run: |
          mkdir Report
      - name: Install Node.js and Newman
        run: |
          curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
          sudo apt-get install -y nodejs
          npm install -g newman
          npm install -g newman-reporter-slackreporter
          npm install -g newman-reporter-htmlextra
        # This step installs Node.js and Newman on the GitHub Actions runner.
      - name: Run API test
        run: |
          newman run "api/test/School_API.postman_collection.json" -e "api/test/School.postman_environment.json" -r cli,htmlextra --reporter-htmlextra-export Report/report.html
      - name: Upload the report
        uses: actions/upload-artifact@v3
        with:
          name: Report
          path: Report
